spring.application.name=cats

# ===============================
# MySQL Database
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/cats
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080